language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  fqdn: mpd.chemphys.ru
  on:
    branch: master
script:
  - "npm run build"
